name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    name: Analyze Project
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run tests
        id: runtests
        run: |
          npm ci
          npm run test